[package]
name = "rays"
version = "0.1.0"
authors = ["Bawer Dagdeviren <bawer@nouantropia.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rays_core = { path = "./rays_core" }
